name: 03-composition-via-ajax
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Test az commands'
      run: |
        az account show
    - name: Log Out From Azure
      run: |
        az logout
        az cache purge
        az account clear